# Configuración para renderizar y PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tu_base_datos}
spring.datasource.username=${DB_USER:tu_usuario}
spring.datasource.password=${DB_PASSWORD:tu_contraseña}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true